# Generated by Django 5.2.5 on 2025-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GITHUB', 'GitHub')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('user', 'user')], default='CASHIER', max_length=10),
        ),
    ]
