# Generated by Django 5.2.5 on 2025-08-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_source_user_github_username_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
