# Generated by Django 5.2.5 on 2025-08-17 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hirerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='hirerequest',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='hirerequest',
            name='applicant_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{7,15}$')]),
        ),
    ]
